# use_frameworks!
use_modular_headers!

target 'SDWebImageSVGNativeCoder_Example' do
  platform :ios, '9.0'
  pod 'SDWebImageSVGNativeCoder', :path => '../'
  pod 'svgnative'

  target 'SDWebImageSVGNativeCoder_Tests' do
    inherit! :search_paths
  end
end

target 'SDWebImageSVGNativeCoder_Example-macOS' do
  platform :osx, '10.15'
  pod 'SDWebImageSVGNativeCoder', :path => '../'
  pod 'svgnative'
end
